language: python

matrix:
  include:
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: 'nightly'
  allow_failures:
  - python: 'nightly'

before_install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade -r requirements-dev.txt
  # only Tested with this streamlink dev version
  - pip install --upgrade git+https://github.com/streamlink/streamlink.git

script:
  - pytest
  - flake8 plugins/
